import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "N-Queen Game",
  description: "Generated by me",
};

export default function RootLayout({children,}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="bg-background">
        {children}
      </body>
    </html>
  );
}
